# Generated by Django 3.0.4 on 2020-05-13 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default='2020-05-13', verbose_name='When')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('what', models.CharField(default='None', max_length=5000, verbose_name='What')),
                ('all_day', models.BooleanField(default=True, verbose_name='All day')),
                ('authuser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EverydayInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(default='How was your day', max_length=10485759)),
                ('format_free', models.CharField(max_length=10485759)),
                ('date', models.DateField(auto_now_add=True)),
                ('format_simple', models.CharField(max_length=200)),
                ('authuser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='everyday', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
