# Generated by Django 3.0.4 on 2020-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When'),
        ),
    ]
