# Generated by Django 3.0.4 on 2020-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0002_auto_20200513_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='End'),
        ),
    ]
