# Generated by Django 3.0.4 on 2020-05-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0004_auto_20200513_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='when',
            field=models.DateField(verbose_name='When'),
        ),
    ]
