# Generated by Django 3.0.4 on 2020-05-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0005_auto_20200513_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='when',
            field=models.DateField(auto_now_add=True, verbose_name='When'),
        ),
    ]
