# Generated by Django 3.0.4 on 2020-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0006_auto_20200520_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='emoji',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
