# Generated by Django 3.0.4 on 2020-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0009_auto_20200521_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='newevent',
            name='emoji',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='newevent',
            name='kw1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newevent',
            name='kw2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newevent',
            name='kw3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
