# Generated by Django 3.0.4 on 2020-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0010_auto_20200528_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
    ]
