# Generated by Django 3.0.4 on 2020-06-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0011_newevent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newevent',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='newevent',
            name='end',
        ),
        migrations.DeleteModel(
            name='EverydayInput',
        ),
    ]
