# Generated by Django 3.0.4 on 2020-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0012_auto_20200610_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='kw3',
            field=models.CharField(default='kw3_default', max_length=100),
        ),
    ]
