# Generated by Django 3.0.4 on 2020-06-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everyday', '0013_auto_20200617_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='kw1',
            field=models.CharField(default='kw1_default', max_length=100),
        ),
        migrations.AlterField(
            model_name='newevent',
            name='kw2',
            field=models.CharField(default='kw2_default', max_length=100),
        ),
    ]
