# Generated by Django 3.0.4 on 2020-05-13 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DansangSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DansangInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contents', models.CharField(max_length=100000)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('first_sentence', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=10000)),
                ('authuser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dansang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
