# Generated by Django 3.0.4 on 2020-05-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dansang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dansanginput',
            name='source',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
