# Generated by Django 3.0.4 on 2020-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dansang', '0002_dansanginput_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DansangSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=10000)),
            ],
        ),
    ]
