# Generated by Django 3.0.4 on 2020-06-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dansang', '0003_dansangsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dansanginput',
            name='source',
        ),
    ]
