# Generated by Django 3.0.4 on 2020-05-13 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('insta', models.CharField(max_length=1000)),
                ('facebook', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('youtube', models.CharField(max_length=1000)),
                ('blog', models.CharField(max_length=1000)),
                ('others', models.CharField(max_length=1000)),
                ('authuser', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
