# Generated by Django 3.0.4 on 2020-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='blog',
            field=models.CharField(default='http://127.0.0.1:8000/tong', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='facebook',
            field=models.CharField(default='http://127.0.0.1:8000/tong', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='insta',
            field=models.CharField(default='http://127.0.0.1:8000/tong', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='linkedin',
            field=models.CharField(default='http://127.0.0.1:8000/tong', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='others',
            field=models.CharField(default='http://127.0.0.1:8000/tong', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='youtube',
            field=models.CharField(default='http://127.0.0.1:8000/tong', max_length=1000),
        ),
    ]
