# Generated by Django 3.0.4 on 2020-05-13 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.CharField(default='-ing', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_ing', models.CharField(default='-ing', max_length=10)),
                ('ing', models.BooleanField()),
                ('desc', models.CharField(max_length=1000)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=10000)),
                ('authuser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
